### PR TITLE
Contact Numbers Web Link + Fixed Home Page

### LINKED ISSUE #31: Update title on home screen for ICU
At the moment the app says "ICU Non-Intensivist"

image

As per the information architecture in our readme it needs to say "ICU for new starters"

https://files.slack.com/files-pri/T2H965QFM-F0105MNNF34/image.png

### PR DESCRIPTION
**Pull request by alessandrofavero**
Fixed #31 

- Fixed title to 'ICU'

Screenshot_1585027962

Implemented #44 

- Contacts Number showing in a browser page.
- Creation of ContactLauncher class for possible migration to direct call

launch_contatacts_browser

### CODE REVIEW

File: lib/view/staff_welfare/your_welfare_view.dart [hunk 1]
```diff
@@ -42,7 +42,7 @@ class YourWelfareView extends StatelessWidget {
                 crossAxisAlignment: CrossAxisAlignment.start,
                 children: <Widget>[
                   _buildSpacer(),
-                  Text('It''s okay to not be okay.', style: AppStyles.textH1),
+                  Text('It' 's okay to not be okay.', style: AppStyles.textH1),
```
Comment (adamkoch) [inline lib/view/staff_welfare/your_welfare_view.dart]: @alessandrofavero extra space?

**Review by adamkoch — APPROVED** [review]
LGTM. One minor comment.

File: lib/view/staff_welfare/your_welfare_view.dart (hunk 1 above)
Comment (alessandrofavero) [reply lib/view/staff_welfare/your_welfare_view.dart]: It should be fixed now. I think it was dartfmt.
