### PR TITLE
Fix for Android Adaptive Icon, Disclaimer and Information screens

### LINKED ISSUE #71: Update Android Launcher Icon and App Name
Make the launcher icon an Android Adaptive Icon, so on devices like Google Pixel, Samsung devices etc. the icon is not just a white circle with the icon very small in the middle of the white circle.

### LINKED ISSUE #167: Disclaimer - UI Inconsistencies
- [x] *A* - Content needs to be indented for sections under "Please keep in mind” and “WHAC19 does not...”
- [x] *B* - Font colour should be grey (Zeplin: #blackAlpha900, 60%)

Simulator Screen Shot - iPhone 5s - 2020-04-04 at 18 17 48

### LINKED ISSUE #195: Information / Disclaimer & Conditions of use - Back button cannot be seen
Bug where the 'back' button in top left on the AppBa is there, but is colored white on white. Functions correctly but cannot be seen.

Note this is probably a theming issue, so avoid hard coding a color: property. Instead investigate the theme color being used.

image

### LINKED ISSUE #216: Information - Copy changes
- [x] **A** Capitalisation and inconsistency - change to "Disclaimer & Conditions of Use”
- [x] **B** Capitalisation - change to "References"

Screenshot (121)

### LINKED ISSUE #217: Information - Icon out of date
- [ ] **C** Icon needs to be updated to the new red icon ✨ 

Screenshot (121)

### PR DESCRIPTION
**Pull request by workerbee22**
Fixes for the following issues:
- Information icon within the app out of date https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/217
- Information copy updates https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/216
- Information / Disclaimer back button is white-on-white https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/195
- Disclaimer font, color and indenting correct as per design https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/167
- Last changes for final Android icon to ensure Adaptive icons work correctly as well as Android legacy icons https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/71

## Changes

Fixed all of the above issues and tested on Android and iOS:
- Fixed Disclaimer back button white-on-white icon button when shown on the Information screen.
- Fixed Disclaimer styling to match standard styles and sizes indent sections as per design
- Fixed several Information screen item titles to be case wording.
- `release-notes.txt` has been updated.

## Screenshots

- Android Adaptive icons as well as legacy icons working correctly for standard shapes:

image

image

Updated Disclaimer and back button visible when viewing from the Information sscreen:

image

## Things to note
Had to rename the Adaptive icon file names to avoid clash with ic_launcher in Android Studio 3.6.x.

### CODE REVIEW

File: lib/view/disclaimer_view.dart [hunk 1]
```diff
@@ -70,43 +70,93 @@ class _DisclaimerViewState extends State<DisclaimerView> {
...
-                            style: Styles.textH3),
-                        Text(
+                        const Text(
+                          'This app is for clinicians and hospital staff use'
+                          ' ONLY\n',
+                          style: Styles.textH3,
+                        ),
+                        const Text(
                           'WHAC19 is an educational tool and interactive cognitive aid for Western Health '
                           'Anaesthetists and ICU doctors 👩‍⚕ 👨‍⚕ who are managing patients with COVID-19 🤒 .'
```
Comment (kimngyn) [inline lib/view/disclaimer_view.dart]:
```suggestion
                          'anaesthetists and ICU doctors 👩‍⚕ 👨‍⚕ who are managing patients with COVID-19 🤒 .'
```

**Review by lukesleeman — APPROVED** [review]
I've tested this out on both a new and old android device, and its looking good ✅

**Review by kimngyn — APPROVED** [review]
LGTM
