### PR TITLE
Fix issue #175

### LINKED ISSUE #175: Your Welfare - UI Inconsistencies
- [x] A - Title too large
- [x] B - Phone icon doesn't match design
- [ ] C - Margins needs to be larger
- [ ] D - Font colour should be black (Zeplin #blackAlpha900)

Note: Broken emojis raised as a separate issue #176

Simulator Screen Shot - iPhone 5s - 2020-04-04 at 22 03 21

### PR DESCRIPTION
**Pull request by rockgecko-development**
Fix issue #175 part A,B,D

**Screenshot:**
image

### CODE REVIEW

File: lib/view/staff_welfare/your_welfare_view.dart [hunk 1]
```diff
@@ -23,11 +24,21 @@ class YourWelfareView extends StatelessWidget {
         iconTheme: Styles.appBarIconTheme,
         title: Text(
           _title,
-          style: Styles.appBarTextStyle,
+          style: Styles.textSemiBold.copyWith(color: AppColors.blackAlpha800),
         ),
         actions: <Widget>[
           IconButton(
-            icon: Icon(Icons.call),
+            icon: Stack(
```
Comment (maks) [inline lib/view/staff_welfare/your_welfare_view.dart:31]: Would it be worth making this stack into a widget? I think we do something similar with PDF icon on another screen?

File: lib/view/staff_welfare/your_welfare_view.dart [hunk 2]
```diff
@@ -93,7 +104,10 @@ class YourWelfareView extends StatelessWidget {
             padding: const EdgeInsets.only(right: 16),
             child: icon,
           ),
-          Expanded(child: Text(text, style: Styles.textP)),
+          Expanded(
+              child: Text(text,
+                  style:
+                      Styles.textP.copyWith(color: AppColors.blackAlpha900))),
```
Comment (maks) [inline lib/view/staff_welfare/your_welfare_view.dart:110]: trailing commas for more consistent formatting pls

**Review by maks — APPROVED** [review]
👍 Great stuff! Just a couple of small points

File: lib/view/staff_welfare/your_welfare_view.dart (hunk 1 above)
Comment (rockgecko-development) [reply lib/view/staff_welfare/your_welfare_view.dart:31]: No, this is definitely specific to this icon. I'm combining an arrow with a phone to make it look like the mock, because I can't extract the image asset from zeplin

**Comment by rockgecko-development** [comment]
@maks CI failed when I removed the trailing comma with `Formatting failed: 1` 
So I put the comma back in.

**Comment by maks** [comment]
> @maks CI failed when I removed the trailing comma with `Formatting failed: 1` 
> So I put the comma back in.

@rockgecko-development hey sorry about the confusion I meant to *add* extra trailing commas.
